var os = require('os')
console.log('您当前操作系统' + os.hostname())
console.log('您当前操作系统名' + os.type())
console.log('编译时的操作系统名' + os.platform())
console.log('cpu系统架构' + os.arch())
console.log('操作系统发行版本' + os.release())
console.log('系统运行时间' + os.uptime())
console.log('系统内存总量' + os.totalmem())
console.log('系统空闲内存' + os.freemem())
console.log('cpu内核信息' + os.cpus())
console.log('网路接口列表' + os.networkInterfaces())